"""new fields in user model

Revision ID: 172fcc5ee4c6
Revises: 18137a7bc6ad
Create Date: 2018-05-28 18:15:23.359751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172fcc5ee4c6'
down_revision = '18137a7bc6ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
